# Generated by Django 4.2.1 on 2023-05-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=50)),
                ('ehflamengo', models.BooleanField()),
                ('ehotaku', models.BooleanField()),
                ('ehsousa', models.BooleanField()),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idfuncionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('codcargo', models.CharField(max_length=20)),
                ('salario', models.FloatField()),
                ('dataadmissao', models.DateField()),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('idveiculo', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('codmarca', models.CharField(max_length=20)),
                ('numportas', models.CharField(max_length=1)),
                ('ano', models.CharField(max_length=4)),
                ('modelo', models.CharField(max_length=30)),
                ('cor', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'veiculo',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('idvenda', models.AutoField(primary_key=True, serialize=False)),
                ('datavenda', models.DateField()),
                ('valorvenda', models.FloatField()),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('idveiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veiculo')),
            ],
            options={
                'db_table': 'venda',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('idservico', models.AutoField(primary_key=True, serialize=False)),
                ('codservico', models.CharField(max_length=20)),
                ('valorservico', models.FloatField()),
                ('dataservico', models.DateField()),
                ('idveiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veiculo')),
            ],
            options={
                'db_table': 'servico',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('idagendamento', models.AutoField(primary_key=True, serialize=False)),
                ('dataagendamento', models.DateField()),
                ('codservico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servico')),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('idveiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veiculo')),
            ],
            options={
                'db_table': 'agendamento',
            },
        ),
    ]
