# Generated by Django 4.2.1 on 2023-05-31 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('codcargo', models.AutoField(primary_key=True, serialize=False)),
                ('nomecargo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=50)),
                ('ehflamengo', models.BooleanField()),
                ('ehotaku', models.BooleanField()),
                ('ehsousa', models.BooleanField()),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idfuncionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dataadmissao', models.DateField(max_length=10)),
                ('codcargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cargo')),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('codmarca', models.AutoField(primary_key=True, serialize=False)),
                ('nomemarca', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('codpagamento', models.AutoField(primary_key=True, serialize=False)),
                ('tipopgto', models.CharField(max_length=30)),
                ('statusconfirmacao', models.BooleanField()),
            ],
            options={
                'db_table': 'pagamento',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('idveiculo', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('numportas', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('modelo', models.CharField(max_length=30)),
                ('cor', models.CharField(max_length=20)),
                ('statusvenda', models.BooleanField()),
                ('codmarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
            ],
            options={
                'db_table': 'veiculo',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('idvenda', models.AutoField(primary_key=True, serialize=False)),
                ('datavenda', models.DateField(max_length=10)),
                ('percentdesconto', models.DecimalField(decimal_places=2, max_digits=3)),
                ('valorvenda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('codpagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pagamento')),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('idfuncionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcionario')),
                ('idveiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veiculo')),
            ],
            options={
                'db_table': 'venda',
            },
        ),
    ]
