# Generated by Django 4.2.1 on 2023-05-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('idveiculo', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('codmarca', models.CharField(max_length=20)),
                ('numportas', models.CharField(max_length=1)),
                ('ano', models.CharField(max_length=4)),
                ('modelo', models.CharField(max_length=30)),
                ('cor', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'veiculo',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
