# Generated by Django 4.2.1 on 2023-05-22 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_veiculo_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=50)),
                ('ehFlamengo', models.BooleanField()),
                ('ehOtaku', models.BooleanField()),
                ('ehSousa', models.BooleanField()),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idFuncionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('codCargo', models.CharField(max_length=20)),
                ('salario', models.FloatField()),
                ('dataAdmissao', models.DateField()),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='codmarca',
            new_name='codMarca',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='idveiculo',
            new_name='idVeiculo',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='numportas',
            new_name='numPortas',
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('idvenda', models.AutoField(primary_key=True, serialize=False)),
                ('dataVenda', models.DateField()),
                ('valorVenda', models.FloatField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('idVeiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veiculo')),
            ],
            options={
                'db_table': 'venda',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('idServico', models.AutoField(primary_key=True, serialize=False)),
                ('codServico', models.CharField(max_length=20)),
                ('valorServico', models.FloatField()),
                ('dataServico', models.DateField()),
                ('idVeiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veiculo')),
            ],
            options={
                'db_table': 'servico',
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('idagendamento', models.AutoField(primary_key=True, serialize=False)),
                ('dataAgendamento', models.DateField()),
                ('codServico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servico')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('idVeiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.veiculo')),
            ],
            options={
                'db_table': 'agendamento',
            },
        ),
    ]
