# Generated by Django 4.2.1 on 2023-05-22 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cliente_funcionario_rename_codmarca_veiculo_codmarca_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agendamento',
            table='Agendamento',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='Cliente',
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='Funcionario',
        ),
        migrations.AlterModelTable(
            name='servico',
            table='Servico',
        ),
        migrations.AlterModelTable(
            name='veiculo',
            table='Veiculo',
        ),
        migrations.AlterModelTable(
            name='venda',
            table='Venda',
        ),
    ]
